import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const handleClick = async (e) => {
    e.preventDefault()
    setLoading(false)
    const target = e.target.amount.value
    fetch(`/api/linear`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: target,
    })
      .then((res) => res.json())
      .then((data) => { setData(data); setLoading(true) })
  }

  return (
    <div>
      <Head>
        <title>AI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-screen h-screen'>
        <section className='flex flex-col justify-center gap-4 max-w-lg mx-auto px-4 h-5/6'>
          <div>
            <h1 className='font-bold text-5xl md:text-6xl'>Regresión lineal</h1>
            <p className='text-end'>Dolares a pesos: <strong>$1 &rarr; $19.44</strong></p>
          </div>
          <div className='space-y-9'>
            <form onSubmit={(e) => handleClick(e)} className='flex flex-col sm:flex-row gap-2'>
              <input type={'number'} min={1} defaultValue={1} name={'amount'} required
                className={`border-2 pl-4 border-[#0070F3] outline-none bg-transparent rounded-lg p-2 w-full placeholder:text-[#3f3f46]`} placeholder={'Cantidad de dolares'} />
              <button type={'submit'} className='bg-[#0070f3] rounded-lg px-3 py-2 text-md font-medium'>
                Convertir
              </button>
            </form>
            <div className={`relative rounded-lg border border-dashed p-4 ${loading ? 'animate-[rerender_1s_ease-in-out_1]' : ''} border-[#3f3f46]`}>
              <div className={`uppercase transition-all duration-300 ${data ? 'absolute leading-4 -top-2.5 tracking-widest flex space-x-1 text-[9px] left-4' : 'top-2 font-bold w-min'}`}>
                <div className={`rounded-full shadow-[0_0_1px_3px_black] ${data ? 'bg-[#27272a] px-1.5' : 'animate-[nodata_1s_ease-in-out_1]'} ${loading ? 'animate-[highlight_1s_ease-in-out_1]' : ''} text-[#71717a]`}>
                  Resultado
                </div>
              </div>
              {data
                ? <strong>${data.predictions[0]} MXN</strong>
                : ''}
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
